<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>false</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>StackerAscom.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Stacker.Core\Stacker.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ASCOM.Platform" Version="7.0.0.1" />
  </ItemGroup>

</Project>
