<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>StackerAscom.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Stacker.Core\Stacker.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ASCOM.Platform" Version="6.5.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Runtime.Serialization" />
  </ItemGroup>

</Project>
