<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <SignAssembly>false</SignAssembly>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Stacker.Core\Stacker.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ASCOM.Platform" Version="6.5.2" />
  </ItemGroup>

</Project>
